function WaveStruct=readdata(folder,name)
% Input the file folder and file name, then use this function to get the
% datastructure in the . mat file. This function is used at the beginning
% to get the waveform information for WiFi, LTE and 5G NR signal. These
% signals is generated by the wireless communication and 5G toolbox

fullMatFileName = fullfile(folder,name);
if ~exist(fullMatFileName, 'file')
  message = sprintf('%s does not exist', fullMatFileName);
  uiwait(warndlg(message));
else
  WaveStruct = load(fullMatFileName);
end